(()=>{'use strict';const $=id=>document.getElementById(id),K=document.body.dataset.lesson,M=models,B='#0069aa',O='#b75000',P='#7236aa';let base=null,run=0,last=0,carry=0;
const v=id=>+$(id).value,f=n=>n.toFixed(1),txt=(x,y,t,c='#183b53',anchor='start')=>`<text x="${x}" y="${y}" text-anchor="${anchor}" style="fill:${c}">${t}</text>`,ln=(x,y,X,Y,c='#cbd9e3',d='')=>`<line x1="${x}" y1="${y}" x2="${X}" y2="${Y}" stroke="${c}" stroke-width="2" stroke-dasharray="${d}"/>`,rect=(x,y,w,h,c,st='none')=>`<rect x="${x}" y="${y}" width="${Math.max(0,w)}" height="${h}" fill="${c}" stroke="${st}" rx="3"/>`,dot=(x,y,c,r=5)=>`<circle cx="${x}" cy="${y}" r="${r}" fill="${c}" stroke="white"/>`;
function metrics(a){$('readouts').innerHTML=a.map(([k,n])=>`<div class="metric">${k}<strong>${n}</strong></div>`).join('')}
function axes(xmax,ymax,xt,yt,xlabel,ylabel,ymin=0){let x=n=>62+n/xmax*655,y=n=>192-(n-ymin)/(ymax-ymin)*151,s=txt(62,20,ylabel);for(let n of yt)s+=ln(62,y(n),717,y(n))+txt(51,y(n)+5,n,'#183b53','end');for(let n of xt)s+=ln(x(n),41,x(n),192,'#e2eaf0')+txt(x(n),212,n,'#183b53','middle');s+=ln(62,41,62,192,'#183b53')+ln(62,192,717,192,'#183b53')+txt(717,233,xlabel,'#183b53','end');return{x,y,s}}
function curve(ps,c){return `<polyline points="${ps.map(p=>p.join(',')).join(' ')}" fill="none" stroke="${c}" stroke-width="3"/>`}
function bar(x,y,w,fs,cs){let s='';fs.forEach((n,i)=>{s+=rect(x,y,w*n,23,cs[i]);x+=w*n});return s}
function render(){document.querySelectorAll('input[type=range]').forEach(el=>$(el.id+'Out').textContent=`${(+el.value).toLocaleString('ja-JP',{maximumFractionDigits:1})} ${el.dataset.unit}`);
if(K==='solubility'){let t=v('temperature'),w=v('water'),total=v('solute'),sub=$('substance').value,r=M.solution(sub,t,w,total);
metrics([['溶けている量',f(r.dissolved)+' g'],['固体の量',f(r.solid)+' g'],['この水量で溶ける限度',f(r.capacity)+' g']]);
let s=txt(35,23,'容器の中（模式図）')+`<path d="M55 35 V155 Q55 164 65 164 H205 Q215 164 215 155 V35" fill="white" stroke="#183b53" stroke-width="3"/>`+rect(57,75,156,86,'#f0f7fa')+ln(58,75,212,75,'#8aabbf');
if(r.solid>1e-6)for(let i=0;i<Math.min(36,Math.ceil(r.solid/4));i++){let x=65+i%12*12,y=151-Math.floor(i/12)*11;s+=`<path d="M${x} ${y} l5 -7 l6 4 l-2 7 h-7 Z" fill="white" stroke="${O}" stroke-width="1.5"/>`}
s+=txt(135,58,t+' ℃','#183b53','middle')+txt(260,49,'入れた物質の内訳（横幅：0〜150 g）')+rect(260,68,450,23,'#e1e8ee')+bar(260,68,450,[r.dissolved/150,r.solid/150],[B,O])+txt(260,116,`溶けている ${f(r.dissolved)} g`,B)+txt(505,116,`固体 ${f(r.solid)} g`,O)+txt(260,152,`水 ${w} g ＋ 物質 ${total} g`);$('scene').innerHTML=s;
let a=axes(80,300,[0,20,40,60,80],[0,100,200,300],'温度（℃）','水100 gあたりの物質の質量（g）');$('plot').innerHTML=a.s+curve([0,20,40,60,80].map(T=>[a.x(T),a.y(M.solubility(sub,T))]),B)+ln(62,a.y(total/w*100),717,a.y(total/w*100),O,'6 5')+ln(a.x(t),192,a.x(t),41,'#627d90','4 4')+dot(a.x(t),a.y(M.solubility(sub,t)),B)+txt(710,35,'青：溶解度　橙の破線：投入量換算','#183b53','end');
$('status').textContent=r.solid>.001?'固体が残っています。温度を変えると？':total===0?'まだ物質を入れていません。':'すべて溶けています。どこまで冷やせる？';if(base!==null)$('comparison').textContent=`記録時 ${f(base)} g → 現在 ${f(r.solid)} g（${r.solid>=base?'+':''}${f(r.solid-base)} g）`;
}else if(K==='humidity'){let t=v('temperature'),total=v('moisture'),r=M.humidity(t,total);metrics([['相対湿度',Math.round(r.rh)+' %'],['結露した水',f(r.liquid)+' g'],['結露開始温度',r.dew===null?'なし':r.dew<0?'0 ℃未満':f(r.dew)+' ℃']]);let s=txt(35,23,'空気 1 m³（模式図）')+rect(38,35,200,125,'#f5fafc','#183b53')+txt(138,85,'水蒸気は見えない','#183b53','middle');if(r.liquid>1e-6)for(let i=0;i<Math.min(25,Math.ceil(r.liquid*2));i++){let x=50+i%10*19,y=149-Math.floor(i/10)*18;s+=`<path d="M${x} ${y-9} Q${x-8} ${y+3} ${x} ${y+4} Q${x+8} ${y+3} ${x} ${y-9}" fill="${O}"/>`}s+=txt(270,46,'水の総量（横幅：0〜40 g）')+rect(270,63,440,23,'#e1e8ee')+bar(270,63,440,[r.vapor/40,r.liquid/40],[B,O])+txt(270,111,`水蒸気 ${f(r.vapor)} g`,B)+txt(505,111,`液体 ${f(r.liquid)} g`,O)+txt(270,149,`この温度の飽和水蒸気量：${f(r.capacity)} g/m³`);$('scene').innerHTML=s;
let a=axes(40,60,[0,10,20,30,40],[0,20,40,60],'温度（℃）','水蒸気量（g/m³）');$('plot').innerHTML=a.s+($('showCurve').checked?curve(Array.from({length:81},(_,i)=>[a.x(i/2),a.y(M.saturation(i/2))]),P):'')+ln(62,a.y(total),717,a.y(total),O,'6 5')+ln(a.x(t),192,a.x(t),a.y(r.vapor),B,'4 4')+dot(a.x(t),a.y(r.vapor),B)+txt(710,35,'青：現在の水蒸気　橙の破線：水の総量','#183b53','end');$('status').textContent=total===0?'水がないので、冷やしても結露しません。':r.liquid>.001?'液体の水ができています。温め直すと？':r.rh>99.99?'飽和しています。少し冷やすと？':'まだ結露していません。何℃で水滴ができる？';
}else{let mass=v('mass'),r=M.phase(v('energy'),mass),q=Math.min(v('energy'),r.max);metrics([['温度',f(r.t)+' ℃'],['状態',r.state],['正味の加熱量',f(q)+' kJ']]);let s='',fs=[r.s,r.l,r.g],cs=[B,O,P];fs.forEach((n,j)=>{let x=30+j*245;s+=rect(x,29,220,107,'#f3f6f9',n>0?cs[j]:'#c4d0d8')+txt(x+110,20,`${['氷','水','水蒸気'][j]} ${f(n*mass)} g`,cs[j],'middle');for(let i=0;i<Math.round(n*30);i++){let px=x+(j===0?26+i%8*24:16+i*(j===1?37:47)%187),py=j===0?55+Math.floor(i/8)*21:j===1?87+i*19%37:45+i*29%77;s+=dot(px,py,cs[j],4)}});s+=bar(30,136,710,fs,cs)+txt(385,175,'同じ水分子を、状態ごとに分けて表示（模式図）','#183b53','middle');$('scene').innerHTML=s;
let a=axes(620,120,[0,100,200,300,400,500,600],[-20,0,40,80,100,120],'−20 ℃の氷から加えた正味の熱量（kJ）','温度（℃）',-20),end=$('showCurve').checked?r.max:q,ps=M.cuts.map(e=>e*mass/1000).filter(n=>n<end).concat([end]);$('plot').innerHTML=a.s+curve(ps.map(n=>[a.x(n),a.y(M.phase(n,mass).t)]),B)+dot(a.x(q),a.y(r.t),O)+txt(710,35,'軸の範囲は固定：質量を変えて比べよう','#183b53','end');$('status').textContent=q>=r.max-.001?'120 ℃に達しました。冷却して戻ってみよう。':r.s>0&&r.l>0?'融解中。熱を加えた分、何が変わっている？':r.l>0&&r.g>0?'沸騰中。熱を加えた分、何が変わっている？':'加熱量と温度の関係を調べよう。';}}
function clear(){base=null;if($('comparison'))$('comparison').textContent='記録すると、固体量の変化を比べられます。'}
function clampEnergy(){if($('energy'))$('energy').value=Math.min(v('energy'),M.phase(0,v('mass')).max)}
document.querySelectorAll('input,select').forEach(el=>el.addEventListener('input',()=>{if(['water','solute','substance'].includes(el.id))clear();if(el.id==='mass'){run=0;$('energy').value=0}if(el.id==='energy'){run=0;clampEnergy()}render()}));$('reset').onclick=()=>{run=0;document.querySelectorAll('input[type=range]').forEach(el=>el.value=el.defaultValue);document.querySelectorAll('input[type=checkbox]').forEach(el=>el.checked=false);if($('substance'))$('substance').selectedIndex=0;clear();render()};document.querySelector('[data-dialog]').onclick=()=>$('model').showModal();
if(K==='phase_change'){function change(d){$('energy').value=Math.max(0,Math.min(M.phase(0,v('mass')).max,v('energy')+d));render()}$('heat').onclick=()=>{run=0;change(10)};$('cool').onclick=()=>{run=0;change(-10)};$('play').onclick=()=>run=1;$('reverse').onclick=()=>run=-1;$('pause').onclick=()=>run=0;function tick(now){let dt=last?Math.min((now-last)/1000,.1):0;last=now;if(run){carry+=dt;if(carry>=.05){change(run*10*carry);carry=0;if(v('energy')<=0||v('energy')>=M.phase(0,v('mass')).max-.01)run=0}}requestAnimationFrame(tick)}requestAnimationFrame(tick)}else{$('heat').onclick=()=>{$('temperature').value=K==='solubility'?60:30;render()};$('cool').onclick=()=>{$('temperature').value=K==='solubility'?20:5;render()};if($('record'))$('record').onclick=()=>{base=M.solution($('substance').value,v('temperature'),v('water'),v('solute')).solid;render()}}render();})();
